FROM oven/bun:1

WORKDIR /usr/src/app

COPY package.json bun.lockb* ./
RUN bun install || true

COPY . .

# Generate Prisma client
RUN bunx prisma generate || true

EXPOSE 3000
CMD sh -c "bunx prisma migrate deploy && bun run dev"
